server:
  port: 8080
  servlet:
    context-path: /admin/client
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9080
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always