local:
  gcp:
    version: 1.0.0.RC1

logging:
  level:
    org.springframework.core.env: warn
    org.springframework.jndi: warn

server:
  compression:
    enabled: true
    mime-types: application/json,text/css,text/html
    min-response-size: 2048

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  resources:
    chain:
      strategy:
        content:
          enabled: true

initializr:
  group-id:
    value: xyz.idean
    description: My
    title: idean
  description:
    value: My description
  package-name:
    value: xyz.ieden